# Generated by Django 3.1.3 on 2020-11-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelzone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='', upload_to='user_image/'),
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
