# Generated by Django 3.1.3 on 2020-11-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelzone', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gold_jewelry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_category', models.CharField(choices=[('rings', 'rings'), ('necklace', 'necklace'), ('earrings', 'earrings'), ('pendants', 'pendants'), ('bangles', 'bangles')], default='', max_length=50)),
                ('gold_name', models.CharField(max_length=40)),
                ('gold_des_code', models.CharField(max_length=10)),
                ('gold_price', models.CharField(max_length=10)),
                ('gold_gross', models.CharField(max_length=10)),
                ('gold_net', models.CharField(max_length=10)),
                ('gold_desc', models.TextField()),
                ('gold_stock', models.CharField(default='Available', max_length=20)),
                ('gold_image', models.ImageField(default='', upload_to='gold_jewelry')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelzone.user')),
            ],
        ),
        migrations.CreateModel(
            name='Diamond_jewelry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamond_category', models.CharField(choices=[('rings', 'rings'), ('necklace', 'necklace'), ('earrings', 'earrings'), ('pendants', 'pendants'), ('bangles', 'bangles')], default='', max_length=50)),
                ('diamond_name', models.CharField(max_length=40)),
                ('diamond_des_code', models.CharField(max_length=10)),
                ('diamond_price', models.CharField(max_length=10)),
                ('diamond_gross', models.CharField(max_length=10)),
                ('diamond_net', models.CharField(max_length=10)),
                ('diamond_desc', models.TextField()),
                ('diamond_stock', models.CharField(default='Available', max_length=20)),
                ('diamond_image', models.ImageField(default='', upload_to='gold_jewelry')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelzone.user')),
            ],
        ),
    ]
