# Generated by Django 3.1.3 on 2020-11-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelzone', '0004_diamond_jewelry_gold_jewelry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gold_jewelry',
            name='gold_desc',
        ),
        migrations.AddField(
            model_name='gold_jewelry',
            name='gold_certification',
            field=models.CharField(default='BIS Hallmark 916', max_length=20),
        ),
        migrations.AddField(
            model_name='gold_jewelry',
            name='gold_metal_colour',
            field=models.CharField(choices=[('yellow', 'yellow'), ('rose', 'rose'), ('two_tone', 'two_tone')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gold_jewelry',
            name='gold_purity',
            field=models.CharField(default='22KT (916)', max_length=10),
        ),
        migrations.AddField(
            model_name='gold_jewelry',
            name='gold_stone_wt',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='gold_jewelry',
            name='gold_category',
            field=models.CharField(choices=[('rings', 'rings'), ('necklace', 'necklace'), ('earrings', 'earrings'), ('pendants', 'pendants'), ('bangles', 'bangles'), ('bracelet', 'bracelet'), ('chains', 'chains')], default='', max_length=50),
        ),
    ]
