# Generated by Django 3.1.3 on 2020-11-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelzone', '0005_auto_20201127_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamond_jewelry',
            name='diamond_desc',
        ),
        migrations.AddField(
            model_name='diamond_jewelry',
            name='diamond_certification',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='diamond_jewelry',
            name='diamond_gender',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='diamond_jewelry',
            name='diamond_gold_certification',
            field=models.CharField(default='BIS Hallmark 750', max_length=20),
        ),
        migrations.AddField(
            model_name='diamond_jewelry',
            name='diamond_gold_purity',
            field=models.CharField(default='18KT (750)', max_length=10),
        ),
        migrations.AddField(
            model_name='diamond_jewelry',
            name='diamond_metal_colour',
            field=models.CharField(choices=[('white', 'white'), ('yellow', 'yellow'), ('rose', 'rose'), ('two_tone', 'two_tone')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gold_jewelry',
            name='gold_gender',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='diamond_jewelry',
            name='diamond_category',
            field=models.CharField(choices=[('rings', 'rings'), ('necklace', 'necklace'), ('earrings', 'earrings'), ('pendants', 'pendants'), ('bangles', 'bangles'), ('bracelet', 'bracelet')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='diamond_jewelry',
            name='diamond_image',
            field=models.ImageField(default='', upload_to='diamond_jewelry'),
        ),
    ]
