# Generated by Django 3.1.3 on 2020-11-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelzone', '0006_auto_20201127_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond_jewelry',
            name='diamond_certification',
            field=models.CharField(default='IGI', max_length=20),
        ),
        migrations.CreateModel(
            name='Platinum_jewelry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platinum_category', models.CharField(choices=[('rings', 'rings'), ('necklace', 'necklace'), ('earrings', 'earrings'), ('pendants', 'pendants'), ('bracelet', 'bracelet'), ('chains', 'chains')], default='', max_length=50)),
                ('platinum_name', models.CharField(max_length=40)),
                ('platinum_des_code', models.CharField(max_length=10)),
                ('platinum_price', models.CharField(max_length=10)),
                ('platinum_gross', models.CharField(max_length=10)),
                ('platinum_net', models.CharField(max_length=10)),
                ('platinum_gender', models.CharField(choices=[('men', 'men'), ('women', 'women')], default='', max_length=20)),
                ('platinum_metal_colour', models.CharField(choices=[('platinum', 'platinum'), ('two_tone', 'two_tone')], default='', max_length=50)),
                ('platinum_purity', models.CharField(default='PT (950)', max_length=10)),
                ('platinum_certification', models.CharField(default='PGI', max_length=20)),
                ('platinum_diamond_certification', models.CharField(default='IGI', max_length=20)),
                ('platinum_stock', models.CharField(default='Available', max_length=20)),
                ('platinum_image', models.ImageField(default='', upload_to='diamond_jewelry')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelzone.user')),
            ],
        ),
    ]
