# Generated by Django 3.1.3 on 2020-11-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelzone', '0007_auto_20201127_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platinum_jewelry',
            name='platinum_certification',
            field=models.CharField(default='PGI', max_length=10),
        ),
        migrations.AlterField(
            model_name='platinum_jewelry',
            name='platinum_diamond_certification',
            field=models.CharField(default='IGI', max_length=10),
        ),
        migrations.AlterField(
            model_name='platinum_jewelry',
            name='platinum_stock',
            field=models.CharField(default='Available', max_length=10),
        ),
    ]
