# Generated by Django 3.1.3 on 2020-11-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelzone', '0009_auto_20201128_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond_jewelry',
            name='diamond_gold_certification',
            field=models.CharField(default='BIS Hallmark 750', max_length=20),
        ),
        migrations.AlterField(
            model_name='diamond_jewelry',
            name='diamond_gold_purity',
            field=models.CharField(default='18KT (750)', max_length=10),
        ),
    ]
