# Generated by Django 3.1.3 on 2020-12-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelzone', '0010_auto_20201128_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold_jewelry',
            name='gold_gender',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gold_jewelry',
            name='gold_metal_colour',
            field=models.CharField(choices=[('yellow', 'yellow'), ('rose', 'rose'), ('two_tone', 'two_tone')], max_length=50),
        ),
    ]
