# Generated by Django 3.1.3 on 2020-12-04 05:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jewelzone', '0011_auto_20201201_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('total_price', models.IntegerField()),
                ('total_qty', models.IntegerField()),
                ('diamond_jewelry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelzone.diamond_jewelry')),
                ('gold_jewelry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelzone.gold_jewelry')),
                ('platium_jewerly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelzone.platinum_jewelry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelzone.user')),
            ],
        ),
    ]
