# Generated by Django 3.1.3 on 2020-12-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelzone', '0012_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='diamond_jewelry',
            new_name='dia_jew',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='gold_jewelry',
            new_name='gold_jew',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='platium_jewerly',
            new_name='pt_jew',
        ),
    ]
