# Generated by Django 3.1.3 on 2020-12-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelzone', '0013_auto_20201204_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='dia_jew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelzone.diamond_jewelry'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='gold_jew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelzone.gold_jewelry'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='pt_jew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelzone.platinum_jewelry'),
        ),
    ]
