# Generated by Django 3.1.3 on 2020-12-04 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jewelzone', '0015_auto_20201204_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('dia_jew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelzone.diamond_jewelry')),
                ('gold_jew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelzone.gold_jewelry')),
                ('pt_jew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelzone.platinum_jewelry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelzone.user')),
            ],
        ),
    ]
